version: 2.1
orbs:
  docker: circleci/docker@1.5.0

jobs:
  test:
    docker:
      - image: cypress/included:8.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Run tests
          command: |
            npm run ci:test

  build:
    docker:
      - image: docker:git
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_ACCESS_TOKEN
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Login to DockerHub
          command: |
            echo $DOCKERHUB_ACCESS_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Build dockerfile
          command: |
            docker build --progress plain -f ./docker-src/Dockerfile --target base -t mobomo/cypress .
            docker build --progress plain -f ./docker-src/Dockerfile --target xpra -t mobomo/cypress:xpra .
            docker push mobomo/cypress:latest
            docker push mobomo/cypress:xpra

workflows:
  version: 2

  build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master